### ISSUE TITLE
Merging PRs back to back can break main, and every check passed on the way in

### ISSUE THREAD

**Issue by picatz** [picatz/flowstate#489]
## What happened

On 2026-08-12, #481, #485, #486 and #487 were merged within about ninety seconds of each other. All four were green: 7 of 7 checks each, on their current heads, against a `main` that at the time contained none of the others.

`main` did not build afterwards:

```
pkg/flowstate/v1/eval.go:1440:56: not enough arguments in call to runNodes
	have (context.Context, []*Node, *Scope, *UndoLog, UndoScope, int)
	want (context.Context, []*Node, *Scope, *UndoLog, UndoScope, int, map[string]struct{})
```

#485 added `runSwitch`, which calls `runNodes` with six arguments. #481 gave `runNodes` a seventh parameter, the set of body step ids whose failure was tolerated. Neither change conflicts textually, so git merged both without complaint, and neither PR's CI ever compiled the other's tree. The first thing to notice the breakage was an unrelated docs-only PR (#488), whose five red jobs had nothing to do with its diff.

The code fix rides in #483, which threads `tolerated` through `runNodeWithVars`, `runNode` and `runSwitch`.

## Why the existing gates cannot catch this

Every check we have answers a question about **one** tree: this branch, merged with the `main` that existed when CI started. A semantic merge conflict is a property of a tree that has never been built anywhere, and it appears at the moment of the second merge. `make check`, the diff-scoped gate, and the required CI jobs are all blind to it by construction, and adding more checks to any of them does not help.

The failure is also silent in the worst way: it does not show up on the PR that causes it. It shows up later, on whoever pushes next, which is how a docs change to three markdown files came to have a red `test` job.

## Options

1. **Require branches to be up to date before merging** (branch protection setting). GitHub then forces each PR to absorb `main` and re-run CI before it can land, so the second merge in a batch cannot happen until the combined tree has actually been built. Costs one CI round trip per PR in a batch, which is exactly the cost of knowing. This is an owner decision, not something an agent can set.
2. **A merge queue**, which does the same thing without the manual rebase, at the price of more moving parts.
3. **A rule for whoever is merging**: after each merge, rebase the next PR onto the new `main` and wait for green before merging it. Free, and only as reliable as the person or agent following it.

Option 1 is the one that cannot be forgotten.

## Related

- The four PRs: #481, #485, #486, #487
- The repair: #483
- The false alarm it produced: #488

**Comment by picatz** [comment]
Decision: the merge queue, not re-verification by hand. Today's wave merged seven pull requests in four hours, each green on its own head against whatever main was when its run started; the gap between "green on the head" and "green on main after the merge" was closed by luck and by one manual merge of main into a branch (#1390 at 50dd17f2), which is exactly the hazard this issue describes.

What lands first, this week, as its own small PR: `ci.yml` gains the `merge_group` event with the plan and verdict jobs deriving their base from `github.event.merge_group.base_sha` (the gate's `-base` channel from #1387 exists for this), and `docs/CI.md` describes the queue's run as the one that decides. Once that is on main, the ruleset flip (require merge queue on `main`) is a one-line settings change; the PR names the exact setting so it can be flipped the moment CI is ready for it. Re-verification (require branches to be up to date) is refused as the primary control: it serializes every merge behind a full CI cycle and still lets two green heads race.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by picatz** [comment]
Correction to the decision above, from checking the tree before building: the CI half already shipped in #688 (`81d352bd`). `ci.yml` triggers on `merge_group`, its concurrency group is keyed on `github.ref` (a queue's `refs/heads/gh-readonly-queue/...` never collides with a PR's `refs/pull/N/merge`) with cancellation disabled for the event, and `tools/gate/ci.go` forces the full job set for any event that is not `pull_request`, so the merge-group lane needs no base at all; `TestTheFullSetRunsWhereBeingWrongIsUnrecoverable/a_merge_group` pins it. `docs/CI.md` already carries the ruleset JSON (require exactly `plan` and `verdict`) and an honest note that the merge-group path is unverified until a queue runs.

So nothing lands for this; the decision stands and the one remaining step is the ruleset flip in the repository settings (Rules → the `main` ruleset → require merge queue, required checks `plan` and `verdict`, per `docs/CI.md`), which the GitHub tooling available to this session cannot perform. The first queued merge is the verification: a `merge_group` run whose plan summary reports every job forced and a green `verdict`. This issue closes on that run.

---
_Generated by [Claude Code](https://claude.ai/code)_
